version: '3.7'
services:

  postgres:
    image: postgres
    container_name: postgres

    environment:
      POSTGRES_PASSWORD: password 
    
    restart: "no"

    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./database/create_database.sql:/docker-entrypoint-initdb.d/create_databases.sql
  
  api:
    container_name: fastapi_microservice

    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    
    restart: "no"

    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8888:8888"


    depends_on:
      - "postgres"

    # environment:
    #   fastapi_host: 0.0.0.0
    #   fastapi_port: 8080
    #   postgress_host: postgres
    #   postgress_password: password
    #   postgress_user: postgres
    #   postgress_db: model_db
    #   dataset_test: /app/database/data.csv
    
    
    # entrypoint: ["python3", "/app/database/session.py"]
    # entrypoint: ["bash", "python3 app/database/session.py && python3 app/main.py"]